import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Button } from '../styles/styled'
import Link from 'next/link'
import { useState } from 'react'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Desafio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>HealthMobile</h1>
          <div className={styles.tela}>

            <Link href="/login">
              <Button style={{margin:10}}>Login</Button>
            </Link>

            <Link href="/store">
              <Button style={{margin:10}}>Cadastro</Button>
            </Link>

          </div>
        
      </main>

        

      <footer className={styles.footer}>
        <a
          href="#" target="_blank" rel="noopener noreferrer">
          <p>Criado por Brenda Raposo</p>
        </a>
      </footer>
    </div>
  )
}
